- block:
    - name: create init directory to master01
      become: true
      when: inventory_hostname == groups['master_servers'][0]
      file:
        path: "{{home_directory}}/init"
        state: directory
        owner: "{{remote_username}}"
        group: "{{remote_username}}"

    - name: Copying kubeadm init config to master01
      become: true
      when: inventory_hostname == groups['master_servers'][0]
      template:
        src: init.config.j2
        dest: "{{home_directory}}/init/init.config"
        mode: "0644"

    - name: initialize the cluster
      when: inventory_hostname == groups['master_servers'][0]
      shell: sudo kubeadm init --config="{{home_directory}}"/init/init.config --upload-certs
      register: output

    - name: saving token info
      when: inventory_hostname == groups['master_servers'][0]
      local_action: copy content={{ output.stdout }} dest="/tmp/token"

    - name: generate token master
      local_action: shell sed -n 72,74p /tmp/token > /tmp/mastertoken

    - name: generate token worker
      local_action: shell sed -n 82,84p /tmp/token > /tmp/workertoken

    - name: create kubeconf directory
      become: true
      when: inventory_hostname == groups['master_servers'][0]
      file:
        path: "{{home_directory}}/.kube"
        state: directory
        owner: "{{remote_username}}"
        group: "{{remote_username}}"

    - name: copy kubeconfig file to home directory
      become: true
      when: inventory_hostname == groups['master_servers'][0]
      copy: 
        src: /etc/kubernetes/admin.conf 
        dest: "{{home_directory}}/.kube/config"
        owner: "{{remote_username}}"
        group: "{{remote_username}}"
        remote_src: yes