- block:
    - name: Restarting containerd services
      become: true
      when: inventory_hostname in ((groups['master_servers'] + groups['worker_servers']) | unique )
      service:
        name: containerd
        state: restarted

    - name: Downloading helm binary
      when: inventory_hostname == groups['master_servers'][0]
      ansible.builtin.get_url:
        url: https://get.helm.sh/helm-v{{helm_version}}-linux-amd64.tar.gz
        dest: /tmp/helm-v{{helm_version}}-linux-amd64.tar.gz

    - name: Unarchiving helm tgz
      when: inventory_hostname == groups['master_servers'][0]
      ansible.builtin.unarchive:
        src: /tmp/helm-v{{helm_version}}-linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Copying helm binary into /usr/local/bin/ 
      when: inventory_hostname == groups['master_servers'][0]
      become: true
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        remote_src: yes
        mode: '0777'

    - name: Download cilium helm chart tgz file
      when: inventory_hostname == groups['master_servers'][0]
      ansible.builtin.get_url:
        url: https://github.com/cilium/charts/raw/master/cilium-{{cilium_version}}.tgz
        dest: /tmp/cilium-{{cilium_version}}.tgz

    - name: Download ingress-nginx helm chart
      when: inventory_hostname == groups['master_servers'][0]
      ansible.builtin.get_url:
        url: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-{{ingress_nginx_version}}/ingress-nginx-{{ingress_nginx_version}}.tgz
        dest: /tmp/ingress-nginx-{{ingress_nginx_version}}.tgz

    - name: Unarchive cilium chart
      when: inventory_hostname == groups['master_servers'][0]
      ansible.builtin.unarchive:
        src: /tmp/cilium-{{cilium_version}}.tgz
        dest: /tmp
        remote_src: yes

    - name: Unarchive ingress-nginx chart
      when: inventory_hostname == groups['master_servers'][0]
      ansible.builtin.unarchive:
        src: /tmp/ingress-nginx-{{ingress_nginx_version}}.tgz
        dest: /tmp
        remote_src: yes

    - name: Deploy Cilium chart from local path
      when: inventory_hostname == groups['master_servers'][0]
      kubernetes.core.helm:
        name: cilium
        chart_ref: /tmp/cilium/
        release_namespace: kube-system
        set_values:
        - value: ipam.mode=kubernetes
        - value: ipam.operator.clusterPoolIPv4PodCIDR="{{pod_subnet}}"

    - name: Pause for 40 seconds
      ansible.builtin.pause:
        seconds: 40
      delegate_to: localhost

    - name: recreate all cluster pods after Cilium installation
      when: inventory_hostname == groups['master_servers'][0]
      shell: kubectl get pods --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork --no-headers=true | grep '<none>' | awk '{print "-n "$1" "$2}' | xargs -L 1 -r kubectl delete pod --force
      ignore_errors: true

    - name: Copying custom ingress value file to the first master node
      become: true
      when: inventory_hostname == groups['master_servers'][0]
      copy:
        src: files/ingress-nginx-values.yaml
        dest: /tmp/ingress-nginx-values.yaml

    - name: Deploy ingress-nginx chart from local path
      when: inventory_hostname == groups['master_servers'][0]
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: /tmp/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        values_files:
          - /tmp/ingress-nginx-values.yaml
